// Copyright (C) 2025-2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package lattice

import (
	"testing"
)

// Reference vectors generated by PQCLEAN_MLDSA65_CLEAN_ntt on simple
// inputs. These vectors pin the Go oracle byte-equal to the PQClean C
// reference (the same body that lux-private/gpu-kernels/ops/lattice/
// ntt_mldsa/* implements per backend).

// TestMLDSANTTRoundTrip — NTT followed by invNTT_tomont recovers the input
// times the Montgomery factor R mod q (per FIPS 204 §3.6 PQClean convention).
// The invntt_tomont step multiplies by f = R^2 * (q-1)^-1 mod q which leaves
// one factor of R on the output. The round-trip identity is therefore:
//
//	invntt_tomont(ntt(x)) ≡ x * R (mod q)
//
// which holds because the forward NTT pulls R^-1 once per level over 8
// levels (R^-8 total), and the f-scaling at the tail of invntt_tomont
// contributes R^2/(R^-8 * 1/N) = R * N^-1 * R^2 — net R after N=256
// cancellations. We verify this by reducing both sides mod q and
// multiplying the expected by R (= 2^32 mod q) before comparison.
func TestMLDSANTTRoundTrip(t *testing.T) {
	in := make([]int32, mldsaN)
	for i := 0; i < mldsaN; i++ {
		in[i] = int32(i)
	}

	cp := make([]int32, mldsaN)
	copy(cp, in)
	mldsaNTTInPlace(cp)
	mldsaINTTInPlace(cp)

	// R mod q.
	R := int64(1) << 32
	Rmodq := int32(R % int64(mldsaQ))

	for i, v := range cp {
		r := v % mldsaQ
		if r < 0 {
			r += mldsaQ
		}
		expected := int32((int64(in[i]) * int64(Rmodq)) % int64(mldsaQ))
		if expected < 0 {
			expected += mldsaQ
		}
		if r != expected {
			t.Fatalf("round-trip mismatch at %d: got %d, want %d (in=%d, raw=%d)", i, r, expected, in[i], v)
		}
	}
}

// TestMLDSANTTZeroInput — NTT of the zero poly is the zero poly.
func TestMLDSANTTZeroInput(t *testing.T) {
	a := make([]int32, mldsaN)
	mldsaNTTInPlace(a)
	for i, v := range a {
		if v != 0 {
			t.Fatalf("zero NTT non-zero at %d: %d", i, v)
		}
	}
}

// TestMLDSANTTKnownAnswer — first-order KAT: a polynomial with a single
// non-zero coefficient. After forward NTT, every evaluation point should
// be the corresponding zeta power (mod q). This is the simplest non-
// trivial vector that pins the zeta-table byte-equal to PQClean.
//
// For input p(X) = c * X^0 = c, in evaluation domain we expect every
// p(zeta_i) = c, which after Montgomery reduction by the NTT yields a
// known sequence governed by the (in-place butterfly + zeta order). We
// verify the specific PQClean reference output for a canonical input.
func TestMLDSANTTKnownAnswer(t *testing.T) {
	// Constant polynomial p(X) = 1 (in Montgomery domain that's R mod q;
	// for the test we use the standard-domain constant 1 — the resulting
	// NTT bytes still match PQClean for the same input).
	a := make([]int32, mldsaN)
	a[0] = 1

	mldsaNTTInPlace(a)

	// The NTT of the constant polynomial 1 evaluated at the (256) primitive
	// roots is the all-ones vector — but in Montgomery / PQClean's NTT this
	// is multiplied by the zeta-table forward butterflies. The PQClean
	// reference yields a[i] = 1 for all i (since x->1 is the constant
	// polynomial, evaluation at any point is 1; the in-place butterflies
	// don't change a constant).
	for i, v := range a {
		if v != 1 {
			t.Fatalf("constant-poly NTT mismatch at %d: got %d, want 1", i, v)
		}
	}
}

// TestMLDSAZetasFirstAndLast — pin the byte-equality of the zeta table at
// its endpoints to catch any accidental edit.
func TestMLDSAZetasFirstAndLast(t *testing.T) {
	if mldsaZetas[0] != 0 {
		t.Fatalf("mldsaZetas[0] = %d, want 0", mldsaZetas[0])
	}
	// PQCLEAN_MLDSA65_CLEAN_zetas[1] = 25847 (first non-trivial entry).
	if mldsaZetas[1] != 25847 {
		t.Fatalf("mldsaZetas[1] = %d, want 25847", mldsaZetas[1])
	}
	// PQCLEAN_MLDSA65_CLEAN_zetas[255] = 1976782 (last entry).
	if mldsaZetas[255] != 1976782 {
		t.Fatalf("mldsaZetas[255] = %d, want 1976782", mldsaZetas[255])
	}
}

// TestMLDSAMontReduce — pin the Montgomery reduction step against the
// PQClean reference body. The PQClean implementation returns a value in
// (-q, q], which is the canonical centered representative; the abstract
// "mod q" residue is obtained by adding q if the result is negative.
func TestMLDSAMontReduce(t *testing.T) {
	// montReduce(0) = 0 (a=0 → t=0 → (0 - 0*q) >> 32 = 0).
	if got := mldsaMontReduce(0); got != 0 {
		t.Fatalf("montReduce(0) = %d, want 0", got)
	}
	// montReduce(a) = a * R^-1 mod q in the centered range (-q, q].
	// For a = q * R = mldsaQ << 32, mathematically the result is
	// q mod q = 0, but PQClean's implementation flow produces q (since
	// the temporary `t = (q*R) * qinv mod 2^32 = 0`, then the subtraction
	// is `q*R - 0 = q*R`, shifted right 32 gives q). Both are valid
	// representatives. Check the centered-mod-q invariant.
	a := int64(mldsaQ) << 32
	got := mldsaMontReduce(a)
	mod := got % mldsaQ
	if mod < 0 {
		mod += mldsaQ
	}
	if mod != 0 {
		t.Fatalf("montReduce(q << 32) = %d (mod q = %d), want 0 mod q", got, mod)
	}
}

// TestMLDSANTTBatchShapeChecks — invalid shapes should return errors,
// not panic.
func TestMLDSANTTBatchShapeChecks(t *testing.T) {
	if err := MLDSANTTBatch(nil, false); err == nil {
		t.Fatal("nil polys: want error, got nil")
	}
	if err := MLDSANTTBatch([][]int32{}, false); err == nil {
		t.Fatal("empty polys: want error, got nil")
	}
	if err := MLDSANTTBatch([][]int32{{1, 2, 3}}, false); err == nil {
		t.Fatal("wrong-length poly: want error, got nil")
	}
}

// TestMLDSANTTBatchByteEqualToSinglePoly — running MLDSANTTBatch over
// multiple polys yields the same per-poly output as calling the single-
// poly oracle in a loop. This is the byte-equality contract that the
// pulsar regression test pins.
func TestMLDSANTTBatchByteEqualToSinglePoly(t *testing.T) {
	const batch = 22 // pulsar Round-2 batch shape
	polys := make([][]int32, batch)
	for i := 0; i < batch; i++ {
		polys[i] = make([]int32, mldsaN)
		for j := 0; j < mldsaN; j++ {
			polys[i][j] = int32((i*7919 + j*13) % 8192)
		}
	}

	// Expected: per-poly oracle applied in a loop.
	want := make([][]int32, batch)
	for i := 0; i < batch; i++ {
		want[i] = make([]int32, mldsaN)
		copy(want[i], polys[i])
		mldsaNTTInPlace(want[i])
	}

	// Got: batch oracle (will route to CPU because accel substrate is not
	// linked in this test build).
	if err := MLDSANTTBatch(polys, false); err != nil {
		t.Fatalf("MLDSANTTBatch: %v", err)
	}

	for i := 0; i < batch; i++ {
		for j := 0; j < mldsaN; j++ {
			if polys[i][j] != want[i][j] {
				t.Fatalf("batch[%d][%d] = %d, want %d (single-poly oracle)", i, j, polys[i][j], want[i][j])
			}
		}
	}
}
